from celery_tasks.algorithms import _DimReduction as DimReduction
from celery_tasks.algorithms import _Classification as Classification
from celery_tasks.algorithms import _Reinforcementlearning as Reinforcementlearning
